### ISSUE TITLE
cosine similarity or euclidean distance for evaluation? 

### ISSUE THREAD

**Issue by Bsting** [yule-li/CosFace#4]
hi, in the paper it stated that "In the testing phase, the testing data is fed into CosFace to extract face features which are later used to compute the cosine similarity score to perform face verification and identification", but it seems like you are using euclidean distance in the test.py. Is there anything i got it wrong?

**Comment by yule-li** [comment]
Cosine similarity is used. I normalize the feature [here](https://github.com/yule-li/CosFace/blob/master/test/test.py#L108) ```in test.py```
