### ISSUE TITLE
Some details confuses me.

### ISSUE THREAD

**Issue by LCorleone** [yule-li/CosFace#5]
hi, first excellent job! but I have some problems.
1. In train_multi_gpu.py, your '_parse_function' use             
```
image = tf.subtract(image,127.5)
image = tf.div(image,128.)
```
However, when testing, you use prewhiten function 
```
def prewhiten(x):
    mean = np.mean(x)
    std = np.std(x)
    std_adj = np.maximum(std, 1.0/np.sqrt(x.size))
    y = np.multiply(np.subtract(x, mean), 1/std_adj)
    return y  
```
It is a little different from above! Will these two different operations of image preprocessing degrades the performance when testing?

2. thank you for providing the pretrained model! Will you release the newest model?

**Comment by yule-li** [comment]
I'm sorry that I forget updating the ```test.py```.  Now the image preprocess within train phase and test phase is consistent.
The lastest trained model is [here](https://pan.baidu.com/s/1c7bPoM_hGvkzp5Tunu_ivg).

**Comment by LCorleone** [comment]
@yule-li 
Thank you so much！I test on my own dataset and it seems that the performance is enhanced.

**Comment by Gabit07** [comment]
> @yule-li
> Thank you so much！I test on my own dataset and it seems that the performance is enhanced.

Hello, I am just curious how many datasets did you use on training?

**Comment by LCorleone** [comment]
@Gabit07 
hello, webface dataset. But till now i find cosface is not so good for face verification. Arcface is more accurate.

**Comment by Gabit07** [comment]
wow, thank you for your quick reply!

**Comment by Gabit07** [comment]
> @Gabit07
> hello, webface dataset. But till now i find cosface is not so good for face verification. Arcface is more accurate.

which implementation in github do you recommend to try?

**Comment by LCorleone** [comment]
@Gabit07   Insightface based on mxnet.
